// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { AppContextProvider } from '@/context/AppContext';
// import { SessionProvider } from "next-auth/react";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       > <SessionProvider> 
//           <AppContextProvider>
//             {children}
//           </AppContextProvider>
//         </SessionProvider> 
//       </body>
//     </html>
//   );
// }





















'use client'; 
import { useEffect, useState } from 'react';
import { Outfit } from 'next/font/google';
import './globals.css';
import { AppContextProvider } from '@/context/AppContext';
import { Toaster } from 'react-hot-toast';
import AnalyticsTracker from '@/components/admin/AnalyticsTracker';
import { SessionProvider } from "next-auth/react";

const outfit = Outfit({ subsets: ['latin'], weight: ['300', '400', '500'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased ${mounted ? outfit.className : ""}`}>
          <SessionProvider> 
            <AppContextProvider>
              <Toaster position="top-right" />
                {children}
            </AppContextProvider>
          </SessionProvider>
      </body>
    </html>
  );
}
