import mongoose from "mongoose";

const propertyCategories = [
  "Apartment/Flat",
  "Duplexes",
  "Detached Houses",
  "Semi-Detached Houses",
  "Bungalows",
  "Mansions",
  "Penthouses",
  "Condominiums",
  "Terraces/Townhouses",
  "Studio Apartments",
  "Mini Flats",
  "Self-Contain Rooms",
  "Office Spaces",
  "Shops/Retail Spaces",
  "Shopping Complexes",
  "Warehouses",
  "Hotels/Motels",
  "Restaurants/Bars",
  "Event Centers/Halls",
  "Co-working Spaces",
  "Fuel Stations",
  "Banks/Financial Buildings",
  "Industrial Properties",
  "Residential Land",
  "Commercial Land",
  "Agricultural Land",
  "Industrial Land",
  "Mixed-Use Land",
  "Estate Land",
  "Waterfront Land",
  "Dry Land",
  "Wet Land",
  "Luxury Apartments",
  "Smart Homes",
  "Beach Houses",
  "Golf Estate Villas",
  "Waterfront Mansions",
  "Serviced Apartments",
  "Private Estates",
  "Short-Term Luxury Rentals",
  "Airbnb-Style Shortlets",
  "Holiday Homes",
  "Guest Houses",
  "Lodges",
  "Vacation Homes",
  "Factories",
  "Industrial Warehouses",
  "Cold Rooms",
  "Power Plants",
  "Logistic Hubs",
  "Storage Facilities",
  "Farmland",
  "Poultry Farms",
  "Fish Farms",
  "Ranches",
  "Plantations",
  "Greenhouses",
  "Mixed-Use Buildings",
  "Estates for Sale",
  "Property Development Sites",
  "Joint Venture (JV) Properties",
  "Rental Income Properties",
  "Distressed/Foreclosure Properties",
  "Schools/Colleges",
  "Hospitals/Clinics",
  "Churches/Mosques",
  "Training Centers",
  "Government Buildings",
  "Newly Built",
  "Renovated",
  "Under Construction",
  "Off-Plan Projects",
  "Furnished Properties",
  "Serviced Properties",
  "Affordable Housing",
  "Smart/Automated Homes",
  "Gated Community Homes",
];

const PropertySchema = new mongoose.Schema(
  {
    userId: { type: String, required: true },
    title: { type: String, required: true },
    description: { type: String, required: true },
    price: { type: Number, required: true },
    features: [{ type: String, required: true }],
    type: {
      type: String,
      enum: ["Rent", "Sale", "Shortlet"],
      required: true,
    },
    category: {
      type: String,
      enum: propertyCategories,
      required: false,
    },
    bedrooms: { type: Number, default: 0 },
    bathrooms: { type: Number, default: 0 },
    toilets: { type: Number, default: 0 },
    area: { type: String },
    country: { type: String, required: true },
    state: { type: String, required: true },
    city: { type: String, required: true },
    address: { type: String, required: true },
    images: [{ type: String, required: true }],
    videos: [{ type: String }],
    visible: { type: Boolean, default: true },
  },
  { timestamps: true }
);

export default mongoose.models.Property ||
  mongoose.model("Property", PropertySchema);
